In [76]:
import scipy.io as io
import numpy as np
import pandas as pd

In [42]:
data1 = io.loadmat('train/data2_train.mat') #读取训练集
data2 = io.loadmat('train/data3_train.mat')
data3 = io.loadmat('train/data5_train.mat')
data4 = io.loadmat('train/data6_train.mat')
data5 = io.loadmat('train/data8_train.mat')
data6 = io.loadmat('train/data10_train.mat')
data7 = io.loadmat('train/data11_train.mat')
data8 = io.loadmat('train/data12_train.mat')
data9 = io.loadmat('train/data14_train.mat')

In [43]:
test = io.loadmat('test/data_test_final.mat') #读取测试集

In [44]:
test = test['data_test_final']

In [45]:
test

array([[3158, 4122, 4145, ..., 1022, 1019, 1010],
       [3023, 3737, 4027, ..., 1019, 1008, 1004],
       [2743, 4388, 4591, ..., 1056, 1030, 1025],
       ...,
       [2561, 3881, 4051, ..., 1018,  998, 1015],
       [2745, 4391, 4335, ..., 1046, 1029, 1019],
       [3009, 3986, 3967, ..., 1011, 1009, 1000]], dtype=uint16)

In [46]:
a = data1['data2_train']
a.shape

(1071, 200)

In [47]:
b = data2['data3_train']
b.shape

(622, 200)

In [48]:
c = data3['data5_train']
c.shape

(362, 200)

In [49]:
d = data4['data6_train']
d.shape

(547, 200)

In [50]:
e = data5['data8_train']
e.shape

(358, 200)

In [51]:
f = data6['data10_train']
f.shape

(729, 200)

In [52]:
g = data7['data11_train']
g.shape

(1841, 200)

In [53]:
h = data8['data12_train']
h.shape

(445, 200)

In [54]:
i = data9['data14_train']
i.shape

(949, 200)

In [55]:
train_data = np.concatenate((data1['data2_train'],data2['data3_train'],data3['data5_train'],data4['data6_train'],data5['data8_train'],data6['data10_train'],data7['data11_train'],data8['data12_train'],data9['data14_train']),axis=0) #将9个训练集的数组放进一个数组里面

In [56]:
train_data.shape

(6924, 200)

In [57]:
train_data

array([[3688, 4381, 4594, ..., 1064, 1034, 1010],
       [2579, 4137, 4412, ..., 1051, 1043, 1005],
       [2581, 4264, 4328, ..., 1054, 1022, 1009],
       ...,
       [2725, 3982, 4099, ..., 1007, 1004, 1008],
       [3320, 3862, 4015, ..., 1007, 1004, 1000],
       [3154, 3986, 4099, ..., 1011,  996, 1003]], dtype=uint16)

In [58]:
a1 = np.array([2]*1071) #创建训练集的标签
b1 = np.array([3]*622)
c1 = np.array([5]*362)
d1 = np.array([6]*547)
e1 = np.array([8]*358)
f1 = np.array([10]*729)
g1 = np.array([10]*1841)
h1 = np.array([12]*445)
i1 = np.array([14]*949)

In [59]:
tt1 = np.append(a1,b1) #将9个训练集标签放进一个数组
tt2 = np.append(tt1,c1)
tt3 = np.append(tt2,d1)
tt4 = np.append(tt3,e1)
tt5 = np.append(tt4,f1)
tt6 = np.append(tt5,g1)
tt7 = np.append(tt6,h1)
train_target = np.append(tt7,i1)

In [60]:
train_target.shape

(6924,)

In [77]:
from sklearn.neighbors import KNeighborsClassifier #导入k近邻模型

In [78]:
knn = KNeighborsClassifier()

In [79]:
knn.fit(train_data,train_target) #学习模型

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [80]:
pred = knn.predict(test) #分类

In [81]:
pred

array([12,  5,  2, ..., 14, 12,  6])

In [82]:
knn_pre = pd.DataFrame(pred) #保存数据
knn_pre.to_csv('knn.csv')

In [83]:
from sklearn import tree #导入决策树模型

In [84]:
clf = tree.DecisionTreeClassifier()

In [85]:
clf.fit(train_data,train_target) #学习模型

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [86]:
pred = clf.predict(test) #分类

In [87]:
pred

array([12,  5,  3, ..., 14,  3,  6])

In [89]:
tree_pre = pd.DataFrame(pred) #保存数据
tree_pre.to_csv('tree.csv')

In [90]:
from sklearn.linear_model import LogisticRegression #导入罗杰斯特模型

In [91]:
log = LogisticRegression()

In [92]:
log.fit(train_data,train_target) #学习模型

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [93]:
pred = log.predict(test) #分类

In [94]:
pred

array([ 3,  5,  3, ..., 14, 12,  6])

In [95]:
log_pre = pd.DataFrame(pred) #保存数据
log_pre.to_csv('logistic.csv')